<div align="center">
   <!-- Histats.com  START (html only)-->
   <a href="http://www.histats.com" alt="page hit counter" target="_blank" >
      <embed src="http://s10.histats.com/2047.swf"  flashvars="jver=1&acsid=1296087&domi=4"  quality="high"  width="280" height="25" name="2047.swf"  align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" wmode="transparent" /></a>
   <img  src="http://sstatic1.histats.com/0.gif?1296087&101" alt="contador gratis" border="0">
   <!-- Histats.com  END  --> 
</div>

<? echo("</div>") ?>

<!--GA Code -->

<p class="plusone">
</p>
<p class="footer">
   <g:plusone href="http://twit-herramientas.com"></g:plusone><br />
   <a href="http://twitter.com/tw_herramientas" class="twitter-follow-button" data-lang="es">Síguenos en @tw_herramientas</a>
   <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
   <br />Creadas originalmente por <a href="http://twitter.com/roobre">Roobre</a>.
</p>
