<!-- Histats.com  START  (standard)-->
<script type="text/javascript">document.write(unescape("%3Cscript src=%27http://s10.histats.com/js15_giftop.js%27 type=%27text/javascript%27%3E%3C/script%3E"));</script>
<a href="http://www.histats.com" target="_blank" title="contador de visitas" ><script  type="text/javascript" >
   try {Histats.startgif(1,1296087,4,10011,"div#histatsC {position: absolute;top:0px;left:0px;}body>div#histatsC {position: fixed;}");
      Histats.track_hits();} catch(err){};
   </script></a>
<noscript><style type="text/css">div#histatsC {position: absolute;top:0px;left:0px;}b</style>
<a href="http://www.histats.com" alt="contador de visitas" target="_blank" ><div id="histatsC"><img border="0" src="http://s4is.histats.com/stats/i/1296087.gif?1296087&103"></div></a>
</noscript>
<!-- Histats.com  END  -->

<p align="center"><a href="/"><img src="http://img.twit-herramientas.com/logo.png" alt="Logo"></a></p>
<a href="/" onclick="if(!confirm('¿Deseas volver al menú principal?'))return false"><img style="position:fixed;bottom:0%; right:2%" src="http://img.twit-herramientas.com/icon.png" alt="Icono"></a>
<? echo('<div style="margin-top: 100px">'); ?>
<!-- <?print_r($_SESSION);?> -->